### ISSUE TITLE
Unable to mix checkpoints packed in safetensors

### ISSUE THREAD

**Issue by fractal-fumbler** [recoilme/losslessmix#1]
many checkpoints, expecially custom ones, saved in safetensors format
when executing mixing command, containing safetensors, there is an error
<details>
<summary>Traceback</summary>

```python
Traceback (most recent call last):
  File "/tmp/yay/losslessmix/losslessmix.py", line 31, in <module>
    a, b, c = loadModelWeights(args.a), loadModelWeights(args.b), loadModelWeights(args.c)
  File "/tmp/yay/losslessmix/losslessmix.py", line 22, in loadModelWeights
    model = torch.load(mPath, map_location=args.device)
  File "/usr/lib/python3.10/site-packages/torch/serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/lib/python3.10/site-packages/torch/serialization.py", line 1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'O'.
```
</details>

if possible, please, add safetensors support :)
ref link -- https://pypi.org/project/safetensors/0.2.7/

**Comment by recoilme** [comment]
Sorry, I'm more interested now in the mixing algorithm itself and experimenting with scales. You may convert in ckpt in automatic1111.

**Comment by fractal-fumbler** [comment]
no problem at all :) thanks a lot for your work
take your time, should i close issue or leave it?
